// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiLUB50IGeO_GFIUOw8Bglr1n9ffpx_bI',
    appId: '1:489723569929:web:119d95bd3b2f1e1bebd5d8',
    messagingSenderId: '489723569929',
    projectId: 'skill-finder-67284',
    authDomain: 'skill-finder-67284.firebaseapp.com',
    storageBucket: 'skill-finder-67284.firebasestorage.app',
    measurementId: 'G-V5KHQZNRYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2ik9Kden3zDHUyUINLJ0JAunL3NDw-j8',
    appId: '1:489723569929:android:ac803e43e633729eebd5d8',
    messagingSenderId: '489723569929',
    projectId: 'skill-finder-67284',
    storageBucket: 'skill-finder-67284.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOIuJijdfG4sBzVo9GjgdRKF28ubJwf5M',
    appId: '1:489723569929:ios:d0b68ebf8c80e879ebd5d8',
    messagingSenderId: '489723569929',
    projectId: 'skill-finder-67284',
    storageBucket: 'skill-finder-67284.firebasestorage.app',
    iosBundleId: 'com.example.skillFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOIuJijdfG4sBzVo9GjgdRKF28ubJwf5M',
    appId: '1:489723569929:ios:d0b68ebf8c80e879ebd5d8',
    messagingSenderId: '489723569929',
    projectId: 'skill-finder-67284',
    storageBucket: 'skill-finder-67284.firebasestorage.app',
    iosBundleId: 'com.example.skillFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiLUB50IGeO_GFIUOw8Bglr1n9ffpx_bI',
    appId: '1:489723569929:web:5841c92bbec153ecebd5d8',
    messagingSenderId: '489723569929',
    projectId: 'skill-finder-67284',
    authDomain: 'skill-finder-67284.firebaseapp.com',
    storageBucket: 'skill-finder-67284.firebasestorage.app',
    measurementId: 'G-EM3ZN6DC62',
  );
}
